server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.117.163.52:3306/module_erupt?serverTimezone=GMT%2B8
    username: erupt
    password: '061600'
    hikari:
      max-lifetime: 30000
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
magic-api:
  web: /magic/web
  banner: true
  resource:
    location: D:/erupt/magic-script
  swagger-config:
    version: 1.0
    description: 后台接口信息
    title: Title
    name: Name
    location: /v2/api-docs/magic-api/swagger2.json