server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.117.163.52:3306/yuyuyu?serverTimezone=GMT%2B8
    username: yuyuyu
    password: '061600'
    hikari:
      max-lifetime: 30000
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update